### PR TITLE
SF-3464: Add Cancellation Token for Aborting Web Requests

### PR DESCRIPTION
**Pull request by jtirjan**

### CODE REVIEW

**Comment by smbecker** [comment]
This feels like a bit of a leaky abstraction. It also shouldn't be limited to only GET requests. Plus this will not work with the `request` module as that uses a [different method](https://github.com/request/request/issues/772) for cancellation.

**Comment by smbecker** [comment]
Should we return a custom `ResponsePromise<T>` object rather than `Promise<T>` and expose a `cancel` method? Or just handle it in the UI using a completely different means altogether by ignoring a stale response rather than explicitly aborting? Thoughts?

**Comment by jtirjan** [comment]
There are some nice benefits to aborting stale requests. I'd prefer to go that route and expose a cancel method. I'll see what the LOE is on creating the custom response.

**Comment by jtirjan** [comment]
I think I got them all. It was super fun.

**Pull request merged**
